\documentclass[fleqn,10pt,lineno]{wlpeerj} % for journal submissions
\usepackage{hyperref}
% \documentclass[fleqn,10pt]{wlpeerj} % for preprint submissions

\title{Using metagenomic methods to detect organismal contaminants in microbial materials.}

\author[1]{Nathan D. Olson}
\author[1]{Justin Zook}
\author[1]{Jayne Morrow}
\author[1]{Nancy Lin}
\affil[1]{Material Measurement Laboratory, National Institute of Standards and Technology}

\keywords{Biodetection, Microbial Material, Reference Material, Purity, Bioinformatics}

\begin{abstract}
High sensitivity methods such as next generation sequencing and PCR are adversely impacted by organismal and DNA contaminants. 
Current methods for detecting contaminants in microbial materials (genomic DNA and cultures) are not sensitive enough and require either a known or culturable contaminant. 
Therefore, higher sensitivity methods not requiring \textit{a priori} assumptions about the contaminant are needed. 
We demonstrate the use of whole genome sequencing (WGS) data and a metagenomic taxonomic classification algorithm for assessing the organismal purity of a microbial material. 
With this method for assessing organismal purity we characterized the types of false positive contaminants reported by the method and how the dependence of detectable contaminant concentration on material genome, contaminant genome, and contaminant proportion using simulated WGS data. 
Using this method to characterize microbial material purity will help to ensure that the materials used to validate pathogen detection assays, generate genome assemblies for database submission, and to benchmarking sequencing methods are free of contaminants adversely impacting measurement results. 
\end{abstract}

\begin{document}

<<include=FALSE>>=
opts_chunk$set(concordance=TRUE)
source("pub_code.R")
@

\flushbottom
\maketitle
\thispagestyle{empty}

\section*{Introduction}
High sensitivity methods such as polymerase chain reaction (PCR) and next generation sequencing (NGS) require higher material and reagent purity than traditional microbiology methods such as culturing, biochemical tests, and microscopy. 
Issues related to reagent contaminants have been well documented and addressed with negative controls \citep{jervis2015deriving}, improved methods for removing contaminants \citep{woyke2011decontamination,motley2014improved}, and post processing of sequence data \citep{mukherjee2015large}. 
However, contaminants in microbial materials such as non-axenic cellular materials and genomic materials with foreign DNA contaminants have only been addressed in data processing \citep{Shrestha2013,tennessen2015prodege}. 

Microbial materials essestially free of contaminants are needed; to populate sequence databases \citep{parks2015checkm}, for mock communities used to validate metagenomic methods \citep{bokulich2016mockrobiota}, to validate biodetection assays \citep{Ieven2013,International2011}, and for basic research using model systems \citep{Shrestha2013}. 
General contaminant assessment is also needed for the characterization of microbial reference materials \citep{olson2016pepr}. 
The inclusion of contaminant characterization results in a reference material report of analysis that allows users to properly determine whether the material is suitable for their application. 
Current methods for detecting contaminants in microbial materials rely on traditional methods such as culture, microscopy, and PCR. 
Culture and microscopy-based methods lack the required sensitivity for NGS and PCR applications, are not appropriate for genomic DNA materials, and assume the contaminants are phenotypically distinct from the material isolate they are contaminating. 
While PCR-based methods can detect contaminants in genomic DNA, the methods are limited as they can only detect targeted contaminants and are not amenable to high-throughput applications \citep{heck2016evaluating,Marron2013}. 
In contrast to these methods, shotgun metagenomic methods can be used to detect contaminants in both cell cultures and genomic DNA materials while only requiring the contaminant has sequencing reads that differentiate it from the material strain. 

Shotgun metagenomic sequencing is used to characterize environmental samples and detect pathogens in clinical samples and is also suitable for detecting contaminants in microbial materials. 
Shotgun metagenomics consists of two main steps, whole genome sequencing of genomic DNA, and analyzing the resulting sequencing data, most commonly using a taxonomic assignment algorithm \citep{Thomas2012}. 
For genomic DNA materials, the material itself is sequenced, whereas genomic DNA must be extracted from cell cultures prior to sequencing. 
After sequencing, a taxonomic assignment algorithm is used to characterize the sequencing data. 
There is a variety of classification algorithms with varying accuracy and computational performance \citep{Bazinet2012,menzel2016fast}.
All methods require a reference database.
In order to detect a contaminant in a microbial material, the contaminating organism (or an organism more closely related to the contaminant than the material) must be in the database. 
As taxonomic classification algorithms are constantly improving, reference databases are expanding, and the cost of sequencing is dropping, shotgun metagenomic sequencing provides an available alternative to current methods for detecting contaminants in microbial materials.

In this work, we present the results from an \textit{in-silico} assessment method to evaluate the suitability of whole genome sequencing data combined with a taxonomic assignment algorithm for detecting contaminant DNA.
This work first provides a baseline assessment of the method using simulated sequencing data from single microorganisms characterizing the types of false positive contaminants the method may report.
Then, the method was challenged for its ability to detect organismal contaminants in microbial material strains using sequencing data simulated to replicate microbial materials with different organismal contaminants at a range of concentrations.

\section*{Methods}
Simulated whole genome sequence data and metagenomic taxonomic classification methods were used to detect and identify foreign DNA in microbial materials. 
Simulated data from individual prokaryotic genomes were used to characterize the rate at which the method correctly classifies reads to at least the material species.
To evaluate contaminant detection we used datasets comprised of pairwise combinations of simulated reads from individual genomes.  

\subsection*{Simulating Sequencing Data}
To approximate real sequencing data reads were simulated using an empirical error model and insert size distribution.
Whole genome sequencing data were simulated using the ART sequencing read simulator \citep{Huang2012}.
Reads were simulated with the Illumina MiSeq error model for 2 $\times$ 230 base pair (bp) paired-end reads with an insert size of 690 $\pm$ 10 bp (average $\pm$ standard deviation) and 20 X mean coverage.
The insert size parameters were defined based on the observed average and standard deviation insert size of the NIST RM8375-MG002 MiSeq sequencing data \citep{olson2016pepr} (NCBI Biosample accession SAMN02854573).

\subsection*{Assessing Taxonomic Composition}
The taxonomic composition of simulated datasets was determined using the Pathoscope sequence taxonomic classifier \citep{Francis2013}.
Pathoscope was selected for two reasons: (1) it uses a large reference database reducing potential biases due to contaminants not represented in the database, and (2) it leverages efficient whole genome read mapping algorithms.
This method uses an expectation maximization algorithm where the sequence data are first mapped to a database comprised of all sequence data in the Genbank nt database.
Then, through an iterative process, it re-assigns ambiguously mapped reads based on the proportion of reads mapped unambiguously to individual taxa in the database.
The Pathoscope 2.0 taxonomic read classification pipeline has three steps; (1) PathoQC - read quality filtering and trimming using the PRINSEQ algorithm \citep{schmieder2011quality}, (2) PathoMap - mapping reads to a reference database using the bowtie2 algorithm \citep{Langmead2012}, and (3) PathoID - expectation-maximization classification algorithm.
The annotated Genbank nt database provided by the PathoScope developers was used as the reference database (\url{ftp://pathoscope.bumc.bu.edu/data/nt\_ti.fa.gz}).

\subsection*{Baseline Assessment Using Individual Genomes}
Simulated sequencing data from individual genomes was used to characterize the false positive contaminants reported by Pathoscope. 
Sequence data was simulated for \Sexpr{sum(single_tbl_df$N)} strains, from 9 genera (Table \ref{tab:single_org}).
We will refer to the genome used to generate the reads as the material genome.
The genomes included in the simulation study were limited to the number of closed genomes in the Genbank database (\url{http://www.ncbi.nlm.nih.gov/genbank/}, accessed 10/18/2013) belonging to the genera of interest (Table \ref{tab:single_org}).
Due to the large number of closed genomes from the genera \textit{Bacillus}, \textit{Escherichia}, and \textit{Salmonella}, genomes from these genera were limited to the species \textit{Bacillus cereus}, \textit{Escherichia coli}, and \textit{Salmonella enterica} respectively.
The taxonomic hierarchy for the material genome and simulated read assignment match levels were determined using the R package, Taxize \citep{TaxizeArticle,TaxizeManual}.

\subsection*{Contaminant Detection Assessment} 

<< contam_simulation, fig.cap = "Diagram of the simulated contaminant dataset workflow for two individual genomes. Contaminant proportions 0.2 and 0.4 are used for demonstration purposes. The reads were initially simulated from individual genomes. The blue genome is twice the size of the orange genome and twice as many reads are simulated for the blue genome compared to the orange in order to obtain the same coverage. The simulated reads were aligned to the reference database using PathoMap. The resulting alignment file, in SAM file format, was randomly subset based on the desired proportions. Complementary subsets of SAM files (e.g. 0.8 material and 0.2 contaminant) from the two genomes were merged to create individual simulated contaminant datasets.  Due to the different sized genomes, the simulated contaminant datasets have different numbers of reads. Taxonomic assignment summary tables were generated from simulated contaminant datasets using PathoID.", echo=FALSE>>=
knitr::include_graphics("figure/contam_simulation.png")
@


Simulated contaminated datasets were used to evaluate how contaminant detection varied by material and contaminant genome over a range of contaminant concentrations.
Representative genomes for 9 of the 10 genera were used to generate the simulated contaminant datasets (Table \ref{tab:contam_table}).
An \textit{Escherichia coli} strain was selected as a representative of both \textit{Escherichia} and \textit{Shigella}, as the genus \textit{Shigella} and species \textit{Escherichia coli} are not phylogenetically resolved \citep{lan2002escherichia}.
For each pairwise combination of representative genomes, the simulated contaminant dataset was comprised of a randomly selected subset of reads from the material and contaminant (Fig. \ref{fig:contam_simulation}).
The simulated datasets were randomly subsampled at defined proportions, with $p$ representing the proportion of reads from the contaminant, and $1-p$ representing the proportion of reads from the material dataset.
A range of contaminant proportions at 10-fold increments was simulated with $p$ ranging from $10^{-1}$ to $10^{-8}$, resulting in 512 simulated contaminant datasets.
This approach simulates the proportions of cells in a contaminated material and not the amount of DNA, assuming unbiased DNA extraction. 
Organisms with larger genomes therefore have more simulated reads.  


To generate the simulated contaminant datasets single organism simulated datasets were first generated for the 8 representative genomes using the same methods as used in the baseline assessment (Fig. \ref{fig:contam_simulation}).
The resulting simulated sequencing data was first processed using the PathoQC and PathoMap steps in the Pathoscope pipeline.
The output from the PathoMap step (SAM file, sequence alignment file \url{https://samtools.github.io/hts-specs/SAMv1.pdf}) for the material and contaminant datasets were subsampled as described above then combined. 
The resulting SAM file was processed by PathoID, the third step in the Pathoscope pipeline.
Subsampling the sam files instead of the simulated sequence files greatly reduces the computational cost of the analysis, as the simulated reads were only processed by the first two steps in Pathoscope pipeline once rather than for every simulated contaminant dataset.


\subsection*{Bioinformatics Pipeline}

%% TODO %%
% Better description for how use of Docker and github promotes repeatability.
%% TODO %%

To facilitate repeatability and transparency, a Docker (\url{www.docker.com}) container is available 
with pre-installed pipeline dependencies (\url{www.registry.hub.docker.com/u/natedolson/docker-pathoscope/}). 
The scripts used to run the simulations are available at \url{https://github.com/nate-d-olson/genomic_purity}.
Additionally, seed numbers for the random number generator were randomly assigned and recorded for each dataset so the simulated datasets used in the study could be regenerated.
Pathoscope results were processed using the statistical programming language R \citep{R}, and intermediate analysis and data summaries were organized using ProjectTemplate \citep{ProjectTemplate} and archived in a GitHub repository (\url{https://github.com/nate-d-olson/genomic_purity_analysis}) along with the source files for this manuscript.

\section*{Results}

\subsection*{Baseline Assessment Using Individual Genomes}

First, we assessed baseline performance of the proposed method for detecting contaminant DNA in microbial materials. 
Our analysis included taxonomic classification results for simulated sequencing data  from \Sexpr{length(spec_prop)} genomes, representing 10 different genera (Table \ref{tab:single_org}). 
For \Sexpr{spec_0.99} of the \Sexpr{length(spec_prop)} genomes, Pathoscope estimated that less than 99\% of the material was the same species as the genome the sequencing data was simulated from (Fig. \ref{fig:species_prop}). 
Of these \Sexpr{spec_0.99} genomes, the estimated proportion of the sequencing data identified as the correct species varied by genus. 
None of the \textit{Shigella} genomes and only five of the 49 \textit{Staphylococcus} genomes had estimated proportions greater than 0.9 for the correct species. 
87 of the 105 genomes with estimated species level match proportions less than 0.99 come from \textit{Shigella}, \textit{Staphylococcus}, or \textit{Escherichia}. 
Excluding \textit{Shigella}, \textit{Escherichia}, and \textit{Staphylococcus}, the median estimated proportion matching at the species level or higher is  \Sexpr{round(non_ec_shig_st_med_spec,4)}. 
We characterized false positive contaminants detected in genomes from the genera \textit{Shigella}, \textit{Escherichia}, and \textit{Staphylococcus}, as well as genomes of other species, match proportions less than 0.9. 
Two types of false positive contaminants were identified: (1) contaminants that were genomically indistinguishable from the material and (2) contaminants due to errors in the reference database.

<<single_org, results='asis', echo=FALSE, message=FALSE>>=
single_tbl_df %>% xtable::xtable(label = "tab:single_org", digits = 2, caption = "Breakdown of the number of genomes by genus used to generate single genome simulated datasets. N indicates the number of genomes, and Genome Size is presented as the median and range (minimum to maximum).") %>%
       print(include.rownames=FALSE, sanitize.text.function = identity)
@

<<species_prop, fig.cap = "Species level or higher estimated match proportion varies by material genus. The proportion of the material was estimated by Pathoscope. The estimated match proportion is the total proportion of the material with correct taxonomic assignments to the genome species, subspecies, strain, or isolate levels. The vertical dashed line indicates the 0.99 match proportion. Orange points are genomes with species level match proportions less than 0.90 and blue points greater than 0.90", echo=FALSE>>=
ggplot(single_species_match) + 
      geom_jitter(aes(x= query_genus_reorder, y = cum_prop,color = match_thresh), 
                  alpha = 0.5, width = 0.25) + 
      geom_hline(aes(yintercept = 0.99), linetype = 2) +
      theme_bw() + theme(axis.text.y = element_text(face = "italic")) + 
      labs(x = "Material Genus", y = "Estimated Match Proportion") + coord_flip() +
      scale_color_manual(values = c("darkblue","darkorange"),guide = FALSE)
@

Two genomes can be genomically indistinguishable if the majority of the two genome sequences are highly similar.
Organisms that are closely related phylogenetically are expected to have large genomic regions with high levels of similarity. 
Phylogenetic similarity is at least partially responsible for the low species level match proportion for  \textit{Shigella} and \textit{Escherichia}, as \textit{Shigella} is not phylogenetically distinct from \textit{E. coli} \citep{lan2002escherichia}.
When including matches to \textit{E. coli} as species level matches, the median match proportions for \textit{Shigella} genomes increases from \Sexpr{round(shig_match_change[2],2)} to \Sexpr{round(shig_match_change[1],2)}. 
Another example of false positives at the species level due to phylogenetic similarity was low match percentage for \textit{Clostridium autoethanogenum} strain DSM10061, where \textit{Clostridium ljungdahlii} strain DSM13528 was assigned the top proportion of reads (\Sexpr{ round(clos_auto_top_value,3)}) instead of \textit{C. autoenthanogenum}. 
False positive contaminants due to phylogenetic similarity are not limited to a closely related species or genus.
\textit{Escherichia coli} strain UMNK88 low match proportions were due to two bacteria in the same family as \textit{E. coli} 
(Enterobacteriaceae): \textit{Providencia stuartii} and \textit{Salmonella enterica} subsp. \textit{enterica} serovar Heidelberg, which had estimated proportions of \Sexpr{ round(ecoli_UMNK88_prov_value, 2)} and \Sexpr{ round(ecoli_UMNK88_sal_value, 2)}, respectively. 
False positives were also due to sharing of genetic material between organisms, such as the sharing of genetic material between bacteria and their phage. 
Phage were identified as false positive contaminants at varying proportions for genomes from all genera investigated, excluding \textit{Francisella} (Fig. \ref{fig:phage_prop}). 
Most notably, the low proportions of species level matches for \textit{E. coli} and \textit{Staphylococcus} are partly due to relatively higher proportions of matches to phage, compared to the other genera investigated. 
Based on phage names all of the false positive phage contaminants were specific to the taxonomy of the genome the sequence data was simulated from.  


%% Genbank - VISTA alignment available for 30 days from 11/16/2016
% \textit{Clostridium autoethanogenum} strain DSM10061 https://www.ncbi.nlm.nih.gov/nuccore/NC_022592.1
% \textit{Clostridium ljungdahlii} strain DSM13528 https://www.ncbi.nlm.nih.gov/nuccore/NC_014328.1 
% Large number of highly similar regions based on VISTA whole genome alignment 
% http://pipeline.lbl.gov/tbrowser/tbrowser/?run=42512-C9RZqeQ4

% \textit{Escherichia coli} strain UMNK88 https://www.ncbi.nlm.nih.gov/nuccore/NC_017641.1
% \textit{Providencia stuartii} https://www.ncbi.nlm.nih.gov/nuccore/NC_017731.1 
% VIST whole genome alignment http://pipeline.lbl.gov/tbrowser/tbrowser/?run=42979-2ayB76PW

% \textit{Escherichia coli} strain UMNK88 https://www.ncbi.nlm.nih.gov/nuccore/NC_017641.1
% \textit{Salmonella enterica} subsp. \textit{enterica} serovar Heidelberg https://www.ncbi.nlm.nih.gov/assembly/GCF_001690135.1 Only compared chromosome  
% VISTA whole genome alignment http://pipeline.lbl.gov/tbrowser/tbrowser/?run=42980-poO1BFgN



<<phage_prop, echo=FALSE, message=FALSE, fig.cap="Estimated proportion of phage in the simulated single genome datasets by genera.  Proportions based on the final estimated proportions for all phage.">>=
ggplot(phage_total) + 
      geom_boxplot(aes(x = query_genus, y = total_phage_guess), color = "darkblue") + 
      labs(x = "Material Genus", y = "Proportion Phage") +
      theme_bw() + theme(axis.text.y = element_text(face = "italic")) +
      coord_flip()
@


False positive contaminants were also due to potential errors in the database such as unclassified or misclassified sequences and the presence of genome assemblies containing in the database including sequence data from organismal or reagent contaminants. 
Low species level match proportions can also be due to the database containing unclassified sequence data for organisms with genomic regions that are highly similar to regions of the material genome. 
For example, the low match proportion for \textit{Pseudomonas} strain FGI182 was due to matches to unclassified bacteria, bacterium 142412, and unclassified \textit{Pseudomonas} species, \textit{Pseudomonas} sp. HF-1. 
The low species proportion of species level matches for \textit{Pseudomonas} strain TKP was also due to potentially misclassified sequences (\textit{Thioalkalivibrio sulfidophilus} strain HL-EbGr7, match proportion 0.0648).
\textit{Bacillus subtilis} BEST7613 genome had low estimated species level match proportion due to \textit{Synechocystis} sp. PCC 6803 substr. PCC-P being estimated as comprising 47\% of the material. 
\textit{Synechocystis} is in a different phylum compared to \textit{Bacillus} (cyanobacteria versus firmicutes) and is a false positive due to a misclassification. 
The \textit{Bacillus subtilis} BEST7613 genome is a synthetic chimeric genome constructed from \textit{Bacillus subtilis} BEST7613 and \textit{Synechocystis} sp. PCC 6803 substr. PCC-P \citep{watanabe2012complete}. 
The genome sequences used to populate the reference database can contain contaminants themselves \citep{parks2015checkm}. 
These database contaminants are responsible for additional false positive contaminants.
The low proportion of species level matches for \textit{Pseudomonas} strain TKP was partially due to contaminated genome sequences in the database (wheat - \textit{Triticum aestivum} match proportion 0.087). 
The eukaryotic false positive contaminants are likely due to contaminants in the material or reagents used to generate the sequencing data used in the assembly \citep{parks2015checkm}. 

\subsection*{Contaminant Detection Assessment}
<<contam_table, results='asis', echo=FALSE, message=FALSE>>=
contam_tbl_df %>% xtable(label = "tab:contam_table", digits = 2,
                         caption = "Representative strains used in simulated contaminant datasets. When available type strains were selected as the representative genome. Species indicates the proportion of the material assigned to the correct species. DNA size (Mb) and Genbank accession numbers (Acc) are indicated for chromosomes (C) and plasmids (P). Aligned Reads is the number of simulated reads aligned to the database by PathoMap.") %>%
      print(include.rownames=FALSE, sanitize.text.function = identity, scalebox='0.65')
@

%% Need to Italicize species names

Finally, contaminant detection was assessed using simulated sequencing data from individual genomes. 
Contaminant datasets were developed by combining subsets of simulated data from two organisms at defined proportions,
with the larger proportion representing the microbial material and smaller proportion the contaminant (Fig. \ref{fig:contam_simulation}).
We simulated contaminant datasets as pairwise combinations of representative genomes from 8 of the genera used in the baseline assessment section of the study (Table \ref{tab:contam_table}).
For all of the genomes selected for the detection assessment study, the estimated proportion of material assigned to the correct species was greater than 0.98 (Table \ref{tab:contam_table}).

%%<<contam_min_table, results='asis', echo=FALSE, message=FALSE>>=
%% contam_min_df %>% xtable(label = "tab:contam_min_table", digits=-1, 
%%     caption = "Lowest proportion of contaminant in each pairwise combination of representativ%e genomes detected.") %>%
%%        print(include.rownames=FALSE, scalebox='0.65')
%%@


The minimum contaminant proportion detected was $1 \times 10^{-3}$ and  $1 \times 10^{-4}$ for most pairwise comparisons with a few notable exceptions. 
When \textit{Y. pestis} was the simulated contaminant, the minimum detected proportion was 0.1 for all material strains. 
For all simulated datasets where \textit{F. tularensis} was the contaminant, the contaminant was not detected.
A few contaminants were detected at proportions as low as $1 \times 10^{-8}$, such as when \textit{Yersinia} contaminated with \textit{E. coli} or \textit{S. enterica} and \textit{E. coli} contaminated with \textit{B. anthracis}. 
However, contaminants detected at lower proportions were false positives for the contaminant due to similar contaminants already present in the material single genome simulated datasets. 
For the \textit{E. coli} material dataset with no simulated contaminants, \Sexpr{contam_esch_species} had an estimated proportion of \Sexpr{signif(contam_esch_prop,3)} resulted in an artificially low contaminant detection proportion in the simulated contaminated dataset. 
The simulated contaminant-free \textit{Y. pestis} material dataset had two false positives resulting in artificially low contaminant detection proportions for \Sexpr{contam_yers_sal_species} with an estimated proportion of \Sexpr{signif(contam_yers_sal_prop,3)} and \Sexpr{contam_yers_esch_species} with an estimated proportion of \Sexpr{signif(contam_yers_esch_prop,3)}.

<<contam_fig, echo = FALSE, message = FALSE, fig.cap = "The relationship between the proportion of contaminant reads simulated per dataset and the proportion of reads matched to the contaminant genus. Plots are split by the material genus with line and point color indicating contaminant genus. Dashed line indicate a 1:1 correlation between matched and expected contaminant reads. ", fig.lp="fig:">>=
contamMixMatchResults %>% mutate(mix = as.numeric(mix), 
                                 mix_contam = if_else(mix != 1, 1 - mix, 0.1e-8)) %>%
      filter(lca_contam_rank %in%
                   c("genus","species","species group","subspecies")) %>%
      mutate(lca_contam_rank = ifelse(lca_contam_rank == "genus", "genus","species")) %>%
      group_by(contam_ds, target_name, contam_name, mix_contam) %>%
      summarise(contam_prop = sum(`Final Guess`)) %>%
            mutate(contam_facet = str_sub(contam_name,1,4),
                   target_facet = str_sub(target_name,1,4),
                   contam_label = str_replace_all(contam_name, "_", " "),
                   contam_label = str_replace(contam_label, " uid.*","")) %>%
      ggplot(aes(x = mix_contam, y = contam_prop)) +
            geom_abline(aes(slope = 1, intercept = 0), linetype = 2, color = "grey60") +
            geom_line(aes(color = contam_facet), alpha = 0.5) +
            geom_point(aes(color = contam_facet), alpha = 0.5) +
            facet_grid(.~target_facet) +
            scale_x_log10() + scale_y_log10() +
            theme_bw() +
            theme(axis.text.x = element_text(angle = 90), legend.position = "bottom") +
            guides(color = guide_legend(nrow = 2)) +
            labs(x = "Contaminant Proportion",
                 y = "Proportion of Matched Reads",
                 color = "Contaminant")
@
%%TODO - add text about points above and below dashed lines as well as missing points.

% <<contam_corr, echo = FALSE, message = FALSE, fig.cap = "Pearson correlation coefficients for estimated and true contaminant proportions.", fig.lp="fig:">>=
% contam_correlation %>% filter(contam_facet != "Yers") %>% 
% ggplot(aes(x = contam_facet, y = target_facet)) + 
%       geom_raster(aes(fill = prop_cor)) + scale_fill_gradient(low = "grey100",high = "grey80") +
%       geom_text(aes(label = round(prop_cor,3))) +
%       theme_bw() + labs(x = "Contaminant", y = "Material")
% @


<<contam_resid, echo = FALSE, message = FALSE, fig.cap = "Total normalized residuals for pairwise combinations of material and contaminant.", fig.lp="fig:">>=
contam_resid_summary %>% 
      ungroup() %>% mutate(target_facet = fct_reorder(target_facet, prop_resid_total, median)) %>% 
      ggplot() + 
            geom_point(aes(x = target_facet, y = prop_resid_total, color = contam_facet)) + theme_bw() +
            labs(x = "Material", y = "Total Normalized Residual", color = "Contaminant") + 
            theme(legend.position = "bottom")
@


Pearson's correlation coefficient was used to determine the correlation between the estimated contaminant and true contaminant proportions for simulated contaminant proportions greater than $0.1 \times 10^{-5}$. 
The estimated and true proportions were strongly correlated for all pairwise comparisons, with an overall median and 95\% confidence interval of \Sexpr{round(contam_corr_quant[2],5)} (\Sexpr{round(contam_corr_quant[1],5)} - \Sexpr{round(contam_corr_quant[3],5)}) (Fig. \ref{fig:contam_fig}). 
Eight of the pairwise comparisons have correlation coefficients below 0.99, all of which have \textit{S. aureus} as either the contaminant or the material. 
Two coefficients were below 0.98: \textit{S. aureus} contaminated with \textit{P. aeruginosa} and \textit{S. enterica}, 0.952 and 0.969 respectively. 
Normalized contaminant proportion residuals, $(estimated-true)/true$, were used to assess the accuracy of the Pathoscope contaminant proportion estimates (Fig. \ref{fig:contam_resid}). 
The material genome strongly influenced the total normalized residuals with \textit{E. coli} and \textit{S. aureus} having consistently higher total normalized residuals compared to the other genomes. 


\section*{Discussion}

The potential for using whole genome sequencing data and taxonomic sequence classification algorithm \textit{Pathoscope} to detect contaminant DNA in microbial materials was evaluated. 
The method requires no \textit{a priori} information about the contaminant and can therefore identify organisms that are known to contaminate the material being analyzed as well as previously unknown contaminants. 
Additionally, as whole genome sequencing can be performed on genomic DNA and cell cultures (after DNA extraction), the method is appropriate for both types of microbial materials.
A baseline assessment of the contaminant DNA detection method using simulated sequencing data generated from individual genomes was performed to characterize the types of false positive contaminants identified by the method was performed. 
The false positive contaminants were split into two categories (1) those due to an inability of the method to differentiate the material genome from the contaminant genome, and (2) those due to errors in the reference database. 
Variations in true contaminant detection were characterized by varying the material, the contaminant, and the level of contamination. 
Overall the method was able to identify contaminant proportions at $1 \times 10^{-3}$ for most pairwise contaminant-material combinations. 
A contaminant proportion of $1 \times 10^{-3}$ is equivalent to 1 contaminant cell per 1,000 cells in a microbial material, or 1,000 contaminant cells/mL of a $1 \times 10^{6}$ culture.
The accuracy of the estimated proportion of the contaminant in the simulated contaminated material varied by contaminant and material strain. 

A primary limitation of the proposed method is the observed false positive contaminants for single genome simulated sequencing data. 
Baseline assessment using simulated sequence data from the microbial material's genome sequence estimates false positives from the method and is a first step in determining the impact of false positives on the method's ability to detect contaminant DNA. 
Additionally, choosing the appropriate database and taxonomic assignment algorithm may help reduce the number of false positive.
Removing sequences from the database for irrelevant contaminants, such as phage, plasmids, vectors, and multicellular eukaryotes would reduce the proportion of false positives. 
By excluding irrelevant contaminants from the database sequencing reads aligning to these irrelevant sequences would no longer result in false positive contaminants. 
Methods for excluding sequence data from a reference database is dependent on the classification algorithm used. 
For example, user-specified sequence data could be removed from the reference database by PathoScope using the PathoDB function. 
Users should be cautious when removing sequences from a reference database when analyzing real data. 
For example, vector sequences from contaminants in sequencing reagents may be incorrectly classified as an organism contaminant. 
Similarly, using a curated database free of misclassified and unclassified sequence data would further help to reduce the proportion of false positive contaminants \citep{tennessen2015prodege}. 
The \textit{Bacillus subtilis}-\textit{Synechocystis} chimeric genome appeared to be a false positive contaminant in the baseline assessment part of this study. 
Pathoscope was used for this proof of concept study as the method uses the full reads and paired-end information for taxonomic classification rather than shorter sequence fragments, $k$-mers. 
Longer sequences allow for better discrimination between highly similar sequences, as the sequences contain more information. 
However, evaluating multiple algorithms using simulated data for the material genome of interest, 
similar to what was done in the baseline assessment part of this study, 
can help determine the optimal classification algorithm for a specific microbial material. 
Regardless of the method and database used, contaminants identified by the method should be evaluated considering the impact of the contaminant on the intended application or the likelihood the contaminant is a false positive. 
For all settings, research, clinical, regulatory, and attribution the contaminant detection method should be validated for the intended application. 
As false positive contaminants are database and taxonomic assignment algorithm dependent, additional work is needed to improve database curation and data authentication efforts as well as characterization of taxonomic assignment algorithm performance.  


Identification and characterization of low abundance contaminants in a non-targeted manner is critical for a material used in high sensitivity assays such as PCR.  
The presence of contaminants that are known to interfere with an assay can be tested using specific assays for thoes contaminants. 
However, specific assays cannot be developed or used to detect unexpectd contaminants that may or may not adversely impact an assay. 
The minimum detected contaminant proportion ranged from $1 \time 10^{-3}$ to $1 \time 10^{-4}$ for most simulated contaminant datasets. 
As the individual datasets were simulated at 20X coverage, \textless 300,000 reads were simulated for each dataset, and on average \textless 3 reads were spiked into the material datasets for simulated contaminant proportions less than $1 \time 10^{-4}$ (Table \ref{tab:contam_table}). 
Unexpectedly low contaminant proportions, $1 \time 10^{-8}$, were detected for \textit{E. coli} contaminated with \textit{B. anthracis} and \textit{Y. pestis} contaminated with \textit{S. enterica} and \textit{E. coli}. 
The low detection proportions were due to false positive contaminants present in the simulated material single genome dataset used to generate the contaminant mixtures. 
For datasets with \textit{Y. pestis} as the simulated contaminant the minimum detected contaminant proportion was 0.1 and \textit{F. tularensis} was not detected in any simulated contaminant datasets. 
It is unclear why \textit{Y. pestis} was detected at a higher proportion relative to the other datasets, $1 \time 10^{-1}$ versus $1 \time 10^{-3}$, and \textit{F. tularensis} was not detected at all. 
One possible reason for the lower contaminant detect for these two organisms is that there are fewer genomes is the database for these two genera. 
Additionally, the \textit{F. tularensis} dataset is much smaller relative to the other genera, less than 90,000 reads. 
With fewer reads in the dataset and genomes in the database, the probability that the randomly selected subset of reads spiked into the simulated material dataset contains reads allowing for contaminant detection is lower. 
While the minimum detected contaminant proportion is important for assessing the suitability of microbial materials for specific applications, quantitative accuracy of the contaminant detection method is important for general material characterization.

The quantitative accuracy of the method varied by material and contaminant. 
For all material-contaminant pairs, the Pathoscope estimated and true contaminant proportions were highly correlated. 
Quantitative accuracy in contaminant proportions is important for applications where acceptable contaminant proportion thresholds are established. 
For example, a microbial material with a contaminant proportion of $1 \time 10^{-5}$ may be acceptable for use in an assay where the contaminant adversely impact an assay when present in proportions greater than $1 \time 10^{-4}$. 
Quantitative accuracy is also relevant when performing a general characterization of the microbial material. 
General contaminant characterization is appropriate for reference materials with more than one use case such as the NIST microbial genomic reference materials (NIST RM8375)\citep{olson2016pepr}.  
Similar to the false positive contaminant baseline assessment, 
simulated data can be used to evaluate the minimal detectable contaminant proportion for specific organisms using different taxonomic assignment algorithms and databases. 

\section*{Conclusions}
With the continual decline in the cost of sequencing and the advances in sequence analysis methods, whole genome sequencing combined with taxonomic assignment algorithms provides a viable alternative to commonly used organismal contaminant detection methods such as culturing, microscopy, and PCR. 
The method presented here is suitable for detecting organismal contaminants in both genomic DNA and whole cell microbial materials, with the only \textit{a priori} assumptions about the contaminants is that they are present in the reference database. 
Furthermore, the method was shown to detect most contaminants when present at $1 \times 10^{-3}$ proportion of cells in a high-throughput manner. 
With the rapid decrease in sequencing cost and ability to detect unknown contaminants at low concentrations, whole genome sequencing is a viable alternative to culture and PCR-based contaminant detection methods. 

\newpage

\section*{Acknowledgments}

The authors would like to thank Dr. Steven Lund for his assistance in developing the study.
The Department of Homeland Security (DHS) Science and Technology Directorate supported this work under the Interagency Agreement HSHQPM-15-T-00019 with the National Institute of Standards and Technology (NIST).
Opinions expressed in this paper are the authors’ and do not necessarily reflect the policies and views of DHS,  NIST, or affiliated venues.
Certain commercial equipment, instruments, or materials are identified in this paper in order to specify the experimental procedure adequately.
Such identification is not intended to imply recommendations or endorsement by NIST,
nor is it intended to imply that the materials or equipment identified are necessarily the best available for the purpose.
Official contribution of NIST; not subject to copyrights in USA.

\bibliography{genomic_purity}

\end{document}
